# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.SmallIntegerField(max_length=11)),
                ('nickname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.SmallIntegerField(choices=[('男', 1), ('女', 2), ('保密', 3)], default=3)),
                ('school', models.CharField(max_length=30)),
                ('hometown', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField()),
                ('mod_time', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
