# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 15:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190120_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='register',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='register',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.SmallIntegerField(choices=[('男', 1), ('女', 2)], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='register',
            name='hometown',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='register',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='register',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.SmallIntegerField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误')], verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='register',
            name='school',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='学校'),
        ),
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
