# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=20, verbose_name='单位'),
        ),
    ]
