# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190123_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityarea',
            name='helves',
            field=models.SmallIntegerField(choices=[('下架', 0), ('上架', 1)], default=1, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='shopsku',
            name='shelves',
            field=models.SmallIntegerField(choices=[('下架', 0), ('上架', 1)], default=1, verbose_name='是否上架'),
        ),
    ]
