# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190124_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityarea',
            name='helves',
            field=models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='是否上架'),
        ),
    ]
